"""Initial migration

Revision ID: 277a0f297c82
Revises: 
Create Date: 2026-08-16 11:39:14.117106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277a0f297c82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('billing_model', sa.Enum('subscription', 'transaction_fee', 'feature_addon', name='billing_model'), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_fee_percent', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('max_active_members', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('tier', sa.Enum('tier_1_informal', 'tier_2_registered', 'tier_3_sacco', name='tenant_tier'), nullable=False),
    sa.Column('isolation_mode', sa.Enum('shared_schema', 'dedicated_schema', name='isolation_mode'), nullable=False),
    sa.Column('dedicated_schema_name', sa.String(length=63), nullable=True),
    sa.Column('chairperson_id_number', sa.String(length=20), nullable=True),
    sa.Column('registration_certificate_url', sa.String(length=500), nullable=True),
    sa.Column('cr12_document_url', sa.String(length=500), nullable=True),
    sa.Column('iprs_verified', sa.Boolean(), nullable=True),
    sa.Column('uses_shared_paybill', sa.Boolean(), nullable=True),
    sa.Column('dedicated_shortcode', sa.String(length=20), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=5), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_domain')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)

    op.create_table('agm_vote_topics',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('opens_at', sa.DateTime(), nullable=False),
    sa.Column('closes_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'cancelled', name='vote_topic_status'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agm_vote_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agm_vote_topics_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('dividend_runs',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('financial_year', sa.Integer(), nullable=False),
    sa.Column('total_pool_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('basis', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', 'disbursed', name='dividend_run_status'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dividend_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dividend_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('savings_schedules',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('frequency', sa.Enum('weekly', 'monthly', 'merry_go_round', name='savings_frequency'), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('penalty_rate', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('grace_period_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('savings_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_schedules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('users',
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('system_admin', 'group_admin', 'branch_leader', 'treasurer', 'member', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=True),
    sa.Column('is_iprs_verified', sa.Boolean(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('preferred_locale', sa.String(length=5), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tenant_id', 'phone_number', name='uq_user_tenant_phone')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('agm_vote_ballots',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('voter_user_id', sa.String(length=36), nullable=False),
    sa.Column('choice', sa.String(length=100), nullable=False),
    sa.Column('signature_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['agm_vote_topics.id'], ),
    sa.ForeignKeyConstraint(['voter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'voter_user_id', name='uq_one_vote_per_member')
    )
    with op.batch_alter_table('agm_vote_ballots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agm_vote_ballots_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('wallets',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('wallet_type', sa.Enum('member', 'group_main', 'sub_purpose', name='wallet_type'), nullable=False),
    sa.Column('sub_purpose', sa.Enum('land', 'welfare', 'project', 'emergency', 'other', name='wallet_sub_purpose'), nullable=True),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('welfare_requests',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('requester_user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('hospitalization', 'bereavement', 'other', name='welfare_category'), nullable=False),
    sa.Column('amount_requested', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_approved', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('supporting_document_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'under_review', 'approved', 'disbursed', 'rejected', name='welfare_status'), nullable=True),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('welfare_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_welfare_requests_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('dividend_allocations',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['dividend_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dividend_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dividend_allocations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mpesa_transactions',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_type', sa.Enum('c2b_contribution', 'b2c_disbursement', 'b2b_settlement', name='mpesa_txn_type'), nullable=False),
    sa.Column('status', sa.Enum('initiated', 'pending_callback', 'reconciled', 'failed', 'unmatched', name='mpesa_txn_status'), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True),
    sa.Column('account_reference', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('raw_callback_payload', sa.JSON(), nullable=True),
    sa.Column('matched_wallet_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matched_wallet_id'], ['wallets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_mpesa_receipt_number'), ['mpesa_receipt_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.Enum('member', 'group', 'system', name='ledger_scope'), nullable=False),
    sa.Column('entry_type', sa.Enum('credit', 'debit', name='ledger_entry_type'), nullable=False),
    sa.Column('source_type', sa.Enum('savings_contribution', 'loan_disbursement', 'loan_repayment', 'welfare_payout', 'dividend_payout', 'fee', 'reversal', name='ledger_source_type'), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('mpesa_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('reverses_entry_id', sa.String(length=36), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mpesa_transaction_id'], ['mpesa_transactions.id'], ),
    sa.ForeignKeyConstraint(['reverses_entry_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('loans',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('borrower_user_id', sa.String(length=36), nullable=False),
    sa.Column('principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_method', sa.Enum('reducing_balance', 'flat_rate', name='interest_method'), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('savings_multiplier_used', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending_appraisal', 'pending_guarantors', 'approved', 'disbursed', 'repaying', 'closed', 'defaulted', 'rejected', name='loan_status'), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(), nullable=True),
    sa.Column('disbursement_mpesa_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disbursement_mpesa_id'], ['mpesa_transactions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('savings_contributions',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('penalty_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=True),
    sa.Column('mpesa_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mpesa_transaction_id'], ['mpesa_transactions.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['savings_schedules.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('savings_contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_contributions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_savings_contributions_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('loan_guarantors',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('guarantor_user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', name='guarantor_status'), nullable=True),
    sa.Column('amount_guaranteed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guarantor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'guarantor_user_id', name='uq_loan_guarantor')
    )
    with op.batch_alter_table('loan_guarantors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_guarantors_loan_id'), ['loan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_guarantors_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_guarantors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_guarantors_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_loan_guarantors_loan_id'))

    op.drop_table('loan_guarantors')
    with op.batch_alter_table('savings_contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_contributions_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_savings_contributions_tenant_id'))

    op.drop_table('savings_contributions')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_loans_tenant_id'))

    op.drop_table('loans')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_tenant_id'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_mpesa_receipt_number'))

    op.drop_table('mpesa_transactions')
    with op.batch_alter_table('dividend_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dividend_allocations_tenant_id'))

    op.drop_table('dividend_allocations')
    with op.batch_alter_table('welfare_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_welfare_requests_tenant_id'))

    op.drop_table('welfare_requests')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_tenant_id'))

    op.drop_table('wallets')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('agm_vote_ballots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agm_vote_ballots_tenant_id'))

    op.drop_table('agm_vote_ballots')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))

    op.drop_table('users')
    op.drop_table('subscriptions')
    with op.batch_alter_table('savings_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_schedules_tenant_id'))

    op.drop_table('savings_schedules')
    with op.batch_alter_table('dividend_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dividend_runs_tenant_id'))

    op.drop_table('dividend_runs')
    with op.batch_alter_table('agm_vote_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agm_vote_topics_tenant_id'))

    op.drop_table('agm_vote_topics')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))

    op.drop_table('tenants')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
